### ISSUE TITLE
Can't install via pip

### ISSUE THREAD

**Issue by gablittledevshop** [pelican-plugins/jinja2content#2]
When I run `pip install pelican-jinja2content` I'm getting this error:

```
Could not find a version that satisfies the requirement pelican-jinja2content (from versions: )
No matching distribution found for pelican-jinja2content
```

Is this plugin publicly available?

**Comment by justinmayer** [comment]
Hi @gablittledevshop.

> Is this plugin publicly available?

Yes, as you can see by tapping the **`PyPI v1.0.1`** badge at the top of the README. I suspect what you are seeing is a dependency resolution problem. Would you please run each of the following commands and then copy & paste the output here?
```bash
python --version

pip --version

pelican --version
```

**Comment by gablittledevshop** [comment]
@justinmayer , you are absolutely right! Sorry about that! I'll close this issue.
